const $=id=>document.getElementById(id), languages=window.LANGUAGES;
let words=[],queue=[],current=null,score=0,answered=0,locked=false,direction='de',lang='pl';
const audioButtons=document.createElement('div');audioButtons.className='row';
const germanButton=document.createElement('button');germanButton.type='button';germanButton.textContent='🔊 Deutsch anhören';
const targetButton=document.createElement('button');targetButton.type='button';targetButton.textContent='🔊 Polnisch anhören';
audioButtons.append(germanButton,targetButton);$('question').after(audioButtons);
function speak(text,locale){if(!('speechSynthesis' in window)){ $('feedback').textContent='Sprachausgabe wird von diesem Browser nicht unterstützt.';return}const utterance=new SpeechSynthesisUtterance(text);utterance.lang=locale;utterance.rate=.85;const voice=speechSynthesis.getVoices().find(v=>v.lang.toLowerCase()===locale.toLowerCase());if(voice)utterance.voice=voice;speechSynthesis.cancel();speechSynthesis.speak(utterance)}
germanButton.onclick=()=>speak(current.de,'de-DE');
targetButton.onclick=()=>speak(current.target,{pl:'pl-PL'}[lang]||lang);
for(const l of languages){const o=document.createElement('option');o.value=l.id;o.textContent=l.name;$('language').append(o)}
$('choose-language').onclick=()=>{lang=$('language').value;$('language-screen').classList.add('hidden');$('menu').classList.remove('hidden');$('intro').textContent='Was möchtest du auf '+languages.find(l=>l.id===lang).name+' üben?'};
$('language-back').onclick=()=>{$('menu').classList.add('hidden');$('language-screen').classList.remove('hidden');$('intro').textContent='Welche Sprache möchtest du lernen?';$('mode-message').textContent=''};
$('mode-words').onclick=()=>{$('menu').classList.add('hidden');$('setup').classList.remove('hidden');$('intro').textContent='In welche Richtung möchtest du üben?'};
for(const [id,name] of [['mode-sentences','Sätze'],['mode-grammar','Grammatik']])$(id).onclick=()=>{$('mode-message').textContent=name+' kommen bald. Im Moment kannst du Wörter üben.'};
function goToMenu(){if('speechSynthesis' in window)speechSynthesis.cancel();$('game').classList.add('hidden');$('setup').classList.add('hidden');$('menu').classList.remove('hidden');$('intro').textContent='Was möchtest du auf '+languages.find(l=>l.id===lang).name+' üben?';$('mode-message').textContent=''}
$('setup-back').onclick=goToMenu;
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function load(l){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=l.file;s.onload=resolve;s.onerror=reject;document.head.append(s)})}
$('start').onclick=async()=>{direction=$('direction').value;try{if(!window.VOCAB?.[lang])await load(languages.find(x=>x.id===lang));words=window.VOCAB[lang];if(words.length<4)throw Error('Mindestens vier Wörter erforderlich');queue=shuffle(words);score=answered=0;$('setup').classList.add('hidden');$('game').classList.remove('hidden');show()}catch(e){$('intro').textContent='Die Wortliste konnte nicht geladen werden: '+e.message}};
$('back').onclick=goToMenu;
function show(){if('speechSynthesis' in window)speechSynthesis.cancel();if(!queue.length)queue=shuffle(words);current=queue.shift();locked=false;$('next').classList.add('hidden');$('feedback').textContent='';$('category').textContent=current.category;$('question').textContent=direction==='de'?current.de:current.target;germanButton.hidden=direction!=='de';targetButton.hidden=direction==='de';targetButton.textContent='🔊 '+(lang==='pl'?'Polnisch':'Wort')+' anhören';$('stats').textContent=`${score} richtig von ${answered}`;const key=direction==='de'?'target':'de';const distractors=shuffle(words.filter(w=>w[key]!==current[key])).slice(0,3);$('answers').replaceChildren();for(const w of shuffle([current,...distractors])){const b=document.createElement('button');b.textContent=w[key];b.onclick=()=>{if(locked)return;locked=true;answered++;if(w===current){score++;b.classList.add('right');$('feedback').textContent='Richtig!'}else{b.classList.add('wrong');$('feedback').textContent=`Richtig ist: ${current[key]}`;queue.splice(Math.min(3,queue.length),0,current);for(const x of $('answers').children)if(x.textContent===current[key])x.classList.add('right')}$('stats').textContent=`${score} richtig von ${answered}`;germanButton.hidden=false;targetButton.hidden=false;$('next').classList.remove('hidden')};$('answers').append(b)}}
$('next').onclick=show;
