const $=id=>document.getElementById(id), languages=window.LANGUAGES;
let words=[],queue=[],current=null,score=0,answered=0,locked=false,direction='de',lang='pl';
const audioButton=document.createElement('button');audioButton.id='listen';audioButton.textContent='🔊 Polnisch anhören';audioButton.type='button';$('question').after(audioButton);
function speakWord(){if(!('speechSynthesis' in window)){ $('feedback').textContent='Sprachausgabe wird von diesem Browser nicht unterstützt.';return}const locale={pl:'pl-PL'}[lang]||lang;const utterance=new SpeechSynthesisUtterance(current.target);utterance.lang=locale;utterance.rate=.85;const voice=speechSynthesis.getVoices().find(v=>v.lang.toLowerCase()===locale.toLowerCase());if(voice)utterance.voice=voice;speechSynthesis.cancel();speechSynthesis.speak(utterance)}
audioButton.onclick=speakWord;
for(const l of languages){const o=document.createElement('option');o.value=l.id;o.textContent=l.name;$('language').append(o)}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function load(l){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=l.file;s.onload=resolve;s.onerror=reject;document.head.append(s)})}
$('start').onclick=async()=>{lang=$('language').value;direction=$('direction').value;try{if(!window.VOCAB?.[lang])await load(languages.find(x=>x.id===lang));words=window.VOCAB[lang];if(words.length<4)throw Error('Mindestens vier Wörter erforderlich');queue=shuffle(words);score=answered=0;$('setup').classList.add('hidden');$('game').classList.remove('hidden');show()}catch(e){$('intro').textContent='Die Wortliste konnte nicht geladen werden: '+e.message}};
$('back').onclick=()=>{if('speechSynthesis' in window)speechSynthesis.cancel();$('game').classList.add('hidden');$('setup').classList.remove('hidden');$('intro').textContent='Welche Sprache möchtest du lernen?'};
function show(){if(!queue.length)queue=shuffle(words);current=queue.shift();locked=false;$('next').classList.add('hidden');$('feedback').textContent='';$('category').textContent=current.category;$('question').textContent=direction==='de'?current.de:current.target;audioButton.hidden=direction==='de';audioButton.textContent='🔊 '+(lang==='pl'?'Polnisch':'Wort')+' anhören';$('stats').textContent=`${score} richtig von ${answered}`;const key=direction==='de'?'target':'de';const distractors=shuffle(words.filter(w=>w[key]!==current[key])).slice(0,3);$('answers').replaceChildren();for(const w of shuffle([current,...distractors])){const b=document.createElement('button');b.textContent=w[key];b.onclick=()=>{if(locked)return;locked=true;answered++;if(w===current){score++;b.classList.add('right');$('feedback').textContent='Richtig!'}else{b.classList.add('wrong');$('feedback').textContent=`Richtig ist: ${current[key]}`;queue.splice(Math.min(3,queue.length),0,current);for(const x of $('answers').children)if(x.textContent===current[key])x.classList.add('right')}$('stats').textContent=`${score} richtig von ${answered}`;audioButton.hidden=false;speakWord();$('next').classList.remove('hidden')};$('answers').append(b)}}
$('next').onclick=show;
