window.GRAMMAR=window.GRAMMAR||{};
window.GRAMMAR.pl=[
// Verbformen: richtige Person im Präsens
{category:'Verbformen',prompt:'Ja ___ w Polsce. (mieszkać)',options:['mieszkam','mieszkasz','mieszka','mieszkamy'],answer:'mieszkam',explanation:'Bei „ja“ (ich) heißt die Form „mieszkam“.',de:'Ich wohne in Polen.',target:'Ja mieszkam w Polsce.'},
{category:'Verbformen',prompt:'Ty ___ w Niemczech. (mieszkać)',options:['mieszkam','mieszkasz','mieszkają','mieszkamy'],answer:'mieszkasz',explanation:'Bei „ty“ (du) heißt die Form „mieszkasz“.',de:'Du wohnst in Deutschland.',target:'Ty mieszkasz w Niemczech.'},
{category:'Verbformen',prompt:'On ___ w domu. (pracować)',options:['pracuję','pracujesz','pracuje','pracujemy'],answer:'pracuje',explanation:'Bei „on“ (er) heißt die Form „pracuje“.',de:'Er arbeitet zu Hause.',target:'On pracuje w domu.'},
{category:'Verbformen',prompt:'My ___ wodę. (pić)',options:['piję','pijesz','pijemy','piją'],answer:'pijemy',explanation:'Bei „my“ (wir) heißt die Form „pijemy“.',de:'Wir trinken Wasser.',target:'My pijemy wodę.'},
{category:'Verbformen',prompt:'Wy ___ książkę. (czytać)',options:['czytam','czytasz','czytacie','czytają'],answer:'czytacie',explanation:'Bei „wy“ (ihr) heißt die Form „czytacie“.',de:'Ihr lest ein Buch.',target:'Wy czytacie książkę.'},
{category:'Verbformen',prompt:'Oni ___ obiad. (jeść)',options:['jem','jesz','jemy','jedzą'],answer:'jedzą',explanation:'Bei „oni“ (sie, Mehrzahl) heißt die Form „jedzą“.',de:'Sie essen zu Mittag.',target:'Oni jedzą obiad.'},
{category:'Verbformen',prompt:'Ja ___ po polsku. (mówić)',options:['mówię','mówisz','mówi','mówimy'],answer:'mówię',explanation:'Bei „ja“ (ich) heißt die Form „mówię“.',de:'Ich spreche Polnisch.',target:'Ja mówię po polsku.'},
{category:'Verbformen',prompt:'Ty ___ kawę. (lubić)',options:['lubię','lubisz','lubi','lubimy'],answer:'lubisz',explanation:'Bei „ty“ (du) heißt die Form „lubisz“.',de:'Du magst Kaffee.',target:'Ty lubisz kawę.'},
{category:'Verbformen',prompt:'Ona ___ do szkoły. (iść)',options:['idę','idziesz','idzie','idziemy'],answer:'idzie',explanation:'Bei „ona“ (sie) heißt die Form „idzie“.',de:'Sie geht zur Schule.',target:'Ona idzie do szkoły.'},
{category:'Verbformen',prompt:'My ___ czas. (mieć)',options:['mam','masz','ma','mamy'],answer:'mamy',explanation:'Bei „my“ (wir) heißt die Form „mamy“.',de:'Wir haben Zeit.',target:'My mamy czas.'},
// Fälle: Form eines Nomens nach Verb oder Präposition
{category:'Fälle',prompt:'Widzę ___. (Hund: pies)',options:['pies','psa','psem','psu'],answer:'psa',explanation:'„Widzę“ (ich sehe) verlangt den Akkusativ: „psa“.',de:'Ich sehe einen Hund.',target:'Widzę psa.'},
{category:'Fälle',prompt:'Piję ___. (Wasser: woda)',options:['woda','wodę','wodzie','wodą'],answer:'wodę',explanation:'Das direkte Objekt steht im Akkusativ: „wodę“.',de:'Ich trinke Wasser.',target:'Piję wodę.'},
{category:'Fälle',prompt:'Idę do ___. (Geschäft: sklep)',options:['sklep','sklepu','sklepem','sklepie'],answer:'sklepu',explanation:'Nach der Präposition „do“ steht der Genitiv: „sklepu“.',de:'Ich gehe zum Geschäft.',target:'Idę do sklepu.'},
{category:'Fälle',prompt:'Jestem w ___. (Schule: szkoła)',options:['szkoła','szkołę','szkole','szkołą'],answer:'szkole',explanation:'Bei einem Ort verlangt „w“ den Lokativ: „szkole“.',de:'Ich bin in der Schule.',target:'Jestem w szkole.'},
{category:'Fälle',prompt:'Rozmawiam z ___. (Mutter: mama)',options:['mama','mamę','mamy','mamą'],answer:'mamą',explanation:'„z“ im Sinn von „mit“ verlangt den Instrumental: „mamą“.',de:'Ich spreche mit meiner Mutter.',target:'Rozmawiam z mamą.'},
{category:'Fälle',prompt:'Nie mam ___. (Zeit: czas)',options:['czas','czasu','czasem','czasowi'],answer:'czasu',explanation:'Bei „nie mam“ steht das Nomen im Genitiv: „czasu“.',de:'Ich habe keine Zeit.',target:'Nie mam czasu.'},
{category:'Fälle',prompt:'Daję książkę ___. (Freund: przyjaciel)',options:['przyjaciel','przyjaciela','przyjacielowi','przyjacielem'],answer:'przyjacielowi',explanation:'Der Empfänger steht im Dativ: „przyjacielowi“.',de:'Ich gebe einem Freund das Buch.',target:'Daję książkę przyjacielowi.'},
{category:'Fälle',prompt:'Jadę do ___. (Warschau: Warszawa)',options:['Warszawa','Warszawę','Warszawy','Warszawą'],answer:'Warszawy',explanation:'Nach „do“ steht der Genitiv: „Warszawy“.',de:'Ich fahre nach Warschau.',target:'Jadę do Warszawy.'},
{category:'Fälle',prompt:'Myślę o ___. (Familie: rodzina)',options:['rodzina','rodzinę','rodzinie','rodziną'],answer:'rodzinie',explanation:'Nach „o“ im Sinn von „über/an“ steht der Lokativ: „rodzinie“.',de:'Ich denke an die Familie.',target:'Myślę o rodzinie.'},
{category:'Fälle',prompt:'Widzę ___. (Katze: kot)',options:['kot','kota','kotem','kotu'],answer:'kota',explanation:'„Widzę“ verlangt den Akkusativ; bei „kot“ lautet er „kota“.',de:'Ich sehe eine Katze.',target:'Widzę kota.'},
// Adjektivformen: Genus und Fall an das Nomen anpassen
{category:'Adjektivformen',prompt:'To jest ___ dom. (groß: duży)',options:['duży','duża','duże','dużego'],answer:'duży',explanation:'„dom“ ist männlich; im Nominativ passt „duży“.',de:'Das ist ein großes Haus.',target:'To jest duży dom.'},
{category:'Adjektivformen',prompt:'To jest ___ książka. (neu: nowy)',options:['nowy','nowa','nowe','nową'],answer:'nowa',explanation:'„książka“ ist weiblich; im Nominativ passt „nowa“.',de:'Das ist ein neues Buch.',target:'To jest nowa książka.'},
{category:'Adjektivformen',prompt:'To jest ___ dziecko. (klein: mały)',options:['mały','mała','małe','małego'],answer:'małe',explanation:'„dziecko“ ist sächlich; im Nominativ passt „małe“.',de:'Das ist ein kleines Kind.',target:'To jest małe dziecko.'},
{category:'Adjektivformen',prompt:'Mam ___ samochód. (neu: nowy)',options:['nowy','nowa','nowe','nowego'],answer:'nowy',explanation:'„samochód“ ist männlich und unbelebtes Objekt; im Akkusativ bleibt hier „nowy“.',de:'Ich habe ein neues Auto.',target:'Mam nowy samochód.'},
{category:'Adjektivformen',prompt:'Kupuję ___ książkę. (interessant: ciekawy)',options:['ciekawy','ciekawa','ciekawe','ciekawą'],answer:'ciekawą',explanation:'Bei „książkę“ (weiblicher Akkusativ) heißt es „ciekawą“.',de:'Ich kaufe ein interessantes Buch.',target:'Kupuję ciekawą książkę.'},
{category:'Adjektivformen',prompt:'Widzę ___ psa. (klein: mały)',options:['mały','mała','małe','małego'],answer:'małego',explanation:'Bei „psa“ (belebter männlicher Akkusativ) heißt es „małego“.',de:'Ich sehe einen kleinen Hund.',target:'Widzę małego psa.'},
{category:'Adjektivformen',prompt:'Piję ___ wodę. (kalt: zimny)',options:['zimny','zimna','zimne','zimną'],answer:'zimną',explanation:'Bei „wodę“ (weiblicher Akkusativ) heißt es „zimną“.',de:'Ich trinke kaltes Wasser.',target:'Piję zimną wodę.'},
{category:'Adjektivformen',prompt:'To jest ___ okno. (neu: nowy)',options:['nowy','nowa','nowe','nowym'],answer:'nowe',explanation:'„okno“ ist sächlich; im Nominativ passt „nowe“.',de:'Das ist ein neues Fenster.',target:'To jest nowe okno.'},
{category:'Adjektivformen',prompt:'Mieszkam w ___ domu. (groß: duży)',options:['duży','dużego','dużym','dużą'],answer:'dużym',explanation:'Bei „w domu“ (Lokativ) heißt es „dużym“.',de:'Ich wohne in einem großen Haus.',target:'Mieszkam w dużym domu.'},
{category:'Adjektivformen',prompt:'Idę z ___ siostrą. (jünger: młodszy)',options:['młodszy','młodsza','młodszą','młodszym'],answer:'młodszą',explanation:'Nach „z“ (mit) steht hier der weibliche Instrumental: „młodszą“.',de:'Ich gehe mit meiner jüngeren Schwester.',target:'Idę z młodszą siostrą.'}
];
